import{useEffect,useState,useCallback}from"react";import{bridgeQueryKey}from"@/lib/bridge";
const SC=({label:l,v,ld}:{label:string;v:any;ld:boolean})=>(<div className="bg-slate-800/60 border border-slate-700 rounded-xl p-4"><div className="text-xs text-slate-500 uppercase tracking-wider mb-1 truncate">{l}</div><div className="text-2xl font-bold text-white font-mono">{ld?<span className="animate-pulse text-slate-600">—</span>:String(v??"—")}</div></div>);
const Sec=({title:t,n,children:c}:{title:string;n?:number;children:React.ReactNode})=>(<div className="bg-slate-800/50 border border-slate-700 rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-slate-700 bg-slate-900/40 flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-300">{t}</h3>{n!==undefined&&<span className="text-xs text-slate-500 font-mono">{n} rows</span>}</div><div className="overflow-x-auto max-h-80">{c}</div></div>);
const DT=({rows,ld,head,row}:{rows:any[];ld:boolean;head:()=>React.ReactNode;row:(r:any,i:number)=>React.ReactNode})=>(ld?<div className="flex items-center justify-center h-24 text-slate-500 text-sm animate-pulse">Loading…</div>:!rows?.length?<div className="flex items-center justify-center h-16 text-slate-600 text-sm">No data</div>:<table className="w-full text-sm"><thead>{head()}</thead><tbody>{rows.map((r,i)=>row(r,i))}</tbody></table>);
const MetricsPage=()=>{
  const[kpis,setKpis]=useState<Record<string,any>>({});
  const[data,setData]=useState<Record<string,any[]>>({});
  const[ld,setLd]=useState(true);
  const[err,setErr]=useState<string|null>(null);
  const load=useCallback(async()=>{setLd(true);setErr(null);try{await Promise.allSettled([
    bridgeQueryKey("metrics_portfolio").then(r=>setData(p=>{...p,"metrics_portfolio":r})).catch(()=>setData(p=>{...p,"metrics_portfolio":[]})),
    bridgeQueryKey("metrics_pos_latest").then(r=>setData(p=>{...p,"metrics_pos_latest":r})).catch(()=>setData(p=>{...p,"metrics_pos_latest":[]})),
    bridgeQueryKey("metrics_business").then(r=>setData(p=>{...p,"metrics_business":r})).catch(()=>setData(p=>{...p,"metrics_business":[]})),
  ]);}catch(e:any){setErr(e.message);}finally{setLd(false);}},[]);
  useEffect(()=>{load();},[load]);
  return(<div className="space-y-6">
    <div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-bold">Metrics</h1><p className="text-slate-500 text-xs mt-0.5 font-mono">page_id:metrics · live · no hardcoded data</p></div><button onClick={load} disabled={ld} className="px-3 py-1.5 text-xs rounded-lg border border-slate-700 text-slate-400 hover:text-white disabled:opacity-40">{ld?"↻ Loading…":"↻ Refresh"}</button></div>
    {err&&<div className="bg-red-900/20 border border-red-500/40 rounded-lg p-3 text-red-400 text-sm font-mono">{err}</div>}
    <div className="space-y-4">
      <Sec title="Portfolio" n={(data["metrics_portfolio"]||[]).length}><DT rows={data["metrics_portfolio"]} ld={ld} head={()=><tr className="border-b border-slate-700 bg-slate-900/50"><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">group_code</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">status</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">cnt</th></tr>} row={(r,i)=><tr key={i} className="border-b border-slate-700/40 hover:bg-slate-700/20"><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["group_code"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["status"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["cnt"]??"—")}</td></tr>}/></Sec>
      <Sec title="POS Latest" n={(data["metrics_pos_latest"]||[]).length}><DT rows={data["metrics_pos_latest"]} ld={ld} head={()=><tr className="border-b border-slate-700 bg-slate-900/50"><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">business_key</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">metric_key</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">metric_value</th></tr>} row={(r,i)=><tr key={i} className="border-b border-slate-700/40 hover:bg-slate-700/20"><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["business_key"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["metric_key"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["metric_value"]??"—")}</td></tr>}/></Sec>
      <Sec title="Business Registry" n={(data["metrics_business"]||[]).length}><DT rows={data["metrics_business"]} ld={ld} head={()=><tr className="border-b border-slate-700 bg-slate-900/50"><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">business_slug</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">status</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">business_stage</th></tr>} row={(r,i)=><tr key={i} className="border-b border-slate-700/40 hover:bg-slate-700/20"><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["business_slug"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["status"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["business_stage"]??"—")}</td></tr>}/></Sec>
    </div>
  </div>);
};
export default MetricsPage;