import{useEffect,useState,useCallback}from"react";import{bridgeQueryKey}from"@/lib/bridge";
const SC=({label:l,v,ld}:{label:string;v:any;ld:boolean})=>(<div className="bg-slate-800/60 border border-slate-700 rounded-xl p-4"><div className="text-xs text-slate-500 uppercase tracking-wider mb-1 truncate">{l}</div><div className="text-2xl font-bold text-white font-mono">{ld?<span className="animate-pulse text-slate-600">—</span>:String(v??"—")}</div></div>);
const Sec=({title:t,n,children:c}:{title:string;n?:number;children:React.ReactNode})=>(<div className="bg-slate-800/50 border border-slate-700 rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-slate-700 bg-slate-900/40 flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-300">{t}</h3>{n!==undefined&&<span className="text-xs text-slate-500 font-mono">{n} rows</span>}</div><div className="overflow-x-auto max-h-80">{c}</div></div>);
const DT=({rows,ld,head,row}:{rows:any[];ld:boolean;head:()=>React.ReactNode;row:(r:any,i:number)=>React.ReactNode})=>(ld?<div className="flex items-center justify-center h-24 text-slate-500 text-sm animate-pulse">Loading…</div>:!rows?.length?<div className="flex items-center justify-center h-16 text-slate-600 text-sm">No data</div>:<table className="w-full text-sm"><thead>{head()}</thead><tbody>{rows.map((r,i)=>row(r,i))}</tbody></table>);
const PricingPage=()=>{
  const[kpis,setKpis]=useState<Record<string,any>>({});
  const[data,setData]=useState<Record<string,any[]>>({});
  const[ld,setLd]=useState(true);
  const[err,setErr]=useState<string|null>(null);
  const load=useCallback(async()=>{setLd(true);setErr(null);try{await Promise.allSettled([
    bridgeQueryKey("pricing_full_list").then(r=>setData(p=>{...p,"pricing_full_list":r})).catch(()=>setData(p=>{...p,"pricing_full_list":[]})),
    bridgeQueryKey("pricing_cat_ranges").then(r=>setData(p=>{...p,"pricing_cat_ranges":r})).catch(()=>setData(p=>{...p,"pricing_cat_ranges":[]})),
  ]);}catch(e:any){setErr(e.message);}finally{setLd(false);}},[]);
  useEffect(()=>{load();},[load]);
  return(<div className="space-y-6">
    <div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-bold">Pricing</h1><p className="text-slate-500 text-xs mt-0.5 font-mono">page_id:pricing · live · no hardcoded data</p></div><button onClick={load} disabled={ld} className="px-3 py-1.5 text-xs rounded-lg border border-slate-700 text-slate-400 hover:text-white disabled:opacity-40">{ld?"↻ Loading…":"↻ Refresh"}</button></div>
    {err&&<div className="bg-red-900/20 border border-red-500/40 rounded-lg p-3 text-red-400 text-sm font-mono">{err}</div>}
    <div className="space-y-4">
      <Sec title="Price List" n={(data["pricing_full_list"]||[]).length}><DT rows={data["pricing_full_list"]} ld={ld} head={()=><tr className="border-b border-slate-700 bg-slate-900/50"><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">product_name</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">category</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">price_amount</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">billing_interval</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">sla_level</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">target_market</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">is_featured</th></tr>} row={(r,i)=><tr key={i} className="border-b border-slate-700/40 hover:bg-slate-700/20"><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["product_name"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["category"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["price_amount"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["billing_interval"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["sla_level"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["target_market"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["is_featured"]??"—")}</td></tr>}/></Sec>
      <Sec title="Category Ranges" n={(data["pricing_cat_ranges"]||[]).length}><DT rows={data["pricing_cat_ranges"]} ld={ld} head={()=><tr className="border-b border-slate-700 bg-slate-900/50"><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">category</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">cnt</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">min_p</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">max_p</th><th className="px-3 py-2 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">avg_p</th></tr>} row={(r,i)=><tr key={i} className="border-b border-slate-700/40 hover:bg-slate-700/20"><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["category"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["cnt"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["min_p"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["max_p"]??"—")}</td><td className="px-3 py-2 text-xs text-slate-300 max-w-[160px] truncate">{String(r["avg_p"]??"—")}</td></tr>}/></Sec>
    </div>
  </div>);
};
export default PricingPage;