export const config = { runtime: 'edge' };

const SUPABASE_URL = 'https://lzfgigiyqpuuxslsygjt.supabase.co';
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6ZmdpZ2l5cXB1dXhzbHN5Z2p0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDQxNzQ2OSwiZXhwIjoyMDU5OTkzNDY5fQ.B6SMaQNb8tER_vqrqkmjNW2BFjcoIowulQOREtRcD8Q';
const INT_TOKEN = process.env.INTERNAL_API_TOKEN || 'rpt-int-t4h-2026';
const BUCKET = 'reports';
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, x-internal-token',
  'Content-Type': 'application/json'
};

function toCSV(rows: any[]): string {
  if (!rows?.length) return '';
  const headers = Object.keys(rows[0]);
  const escape = (v: any) => {
    const s = v === null || v === undefined ? '' : String(v);
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return [
    headers.join(','),
    ...rows.map(row => headers.map(h => escape(row[h])).join(','))
  ].join('\n');
}

async function uploadToStorage(path: string, body: string, mimeType: string): Promise<string | null> {
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${path}`, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      'Content-Type': mimeType,
      'x-upsert': 'true',
    },
    body,
  });
  if (!r.ok) return null;
  return path;
}

async function getSignedUrl(path: string, expiresIn = 604800): Promise<string | null> {
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/sign/${BUCKET}/${path}`, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ expiresIn }),
  });
  if (!r.ok) return null;
  const d = await r.json();
  return `${SUPABASE_URL}/storage/v1${d.signedURL}`;
}

export default async function handler(req: Request) {
  if (req.method === 'OPTIONS') return new Response(null, { status: 200, headers: CORS });

  const _tok = req.headers.get('x-internal-token');
  if (!_tok || _tok !== INT_TOKEN) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: CORS });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'POST only' }), { status: 405, headers: CORS });
  }

  const body = await req.json();
  const packSlug: string = body.slug;
  const period: string = body.period || new Date().toISOString().slice(0, 7); // YYYY-MM
  const baseUrl = `${new URL(req.url).protocol}//${new URL(req.url).host}`;

  if (!packSlug) {
    return new Response(JSON.stringify({ error: 'slug required' }), { status: 400, headers: CORS });
  }

  try {
    // 1. Run the pack
    const packRes = await fetch(`${baseUrl}/api/rpt/pack?slug=${encodeURIComponent(packSlug)}`, {
      headers: { 'x-internal-token': INT_TOKEN }
    });
    const pack = await packRes.json();

    if (pack.error) {
      return new Response(JSON.stringify({ error: pack.error }), { status: 400, headers: CORS });
    }

    // 2. Run each report individually to get full data
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const exportDir = `packs/${packSlug}/${period}/${timestamp}`;
    const files: { name: string; path: string; signed_url: string | null; rows: number }[] = [];

    for (const rpt of (pack.reports || [])) {
      const rptRes = await fetch(`${baseUrl}/api/rpt/report?slug=${encodeURIComponent(rpt.report_slug)}`, {
        headers: { 'x-internal-token': INT_TOKEN }
      });
      const rptData = await rptRes.json();
      const rows = rptData.data || [];

      if (rows.length === 0) continue;

      // Upload CSV
      const csv = toCSV(rows);
      const fileName = `${rpt.report_slug.replace(/\./g, '_')}.csv`;
      const filePath = `${exportDir}/${fileName}`;
      await uploadToStorage(filePath, csv, 'text/csv');
      const signedUrl = await getSignedUrl(filePath);
      files.push({ name: rpt.name || rpt.report_slug, path: filePath, signed_url: signedUrl, rows: rows.length });
    }

    // 3. Build manifest JSON
    const manifest = {
      pack_slug: packSlug,
      pack_name: pack.pack_name,
      period,
      generated_at: new Date().toISOString(),
      rag: pack.rag,
      readiness_pct: pack.readiness_pct,
      files,
      note: 'Generated by T4H Report Factory. Internal use only. Not for external distribution without authorisation.'
    };
    const manifestPath = `${exportDir}/manifest.json`;
    await uploadToStorage(manifestPath, JSON.stringify(manifest, null, 2), 'application/json');
    const manifestUrl = await getSignedUrl(manifestPath);

    // 4. Log to rpt_run
    const now = new Date().toISOString();
    await fetch(`${SUPABASE_URL}/rest/v1/rpt_run`, {
      method: 'POST',
      headers: {
        apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`,
        'Content-Type': 'application/json', Prefer: 'return=minimal'
      },
      body: JSON.stringify({
        report_slug: packSlug, run_type: 'export', status: 'success',
        row_count: files.reduce((s, f) => s + f.rows, 0),
        error_summary: null, requested_by: 'troy', requested_via: 'export_api',
        started_at: now, finished_at: now
      })
    });

    return new Response(JSON.stringify({
      pack_slug: packSlug,
      pack_name: pack.pack_name,
      period,
      rag: pack.rag,
      readiness_pct: pack.readiness_pct,
      file_count: files.length,
      total_rows: files.reduce((s, f) => s + f.rows, 0),
      files,
      manifest_url: manifestUrl,
      export_dir: exportDir,
      generated_at: new Date().toISOString()
    }), { status: 200, headers: CORS });

  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500, headers: CORS });
  }
}
